# Generated by Django 3.2.18 on 2023-03-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230316_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', through='recipes.IngredientAmount', to='recipes.Ingredient', verbose_name='Ингридиенты'),
        ),
    ]
