# Generated by Django 3.2.18 on 2023-03-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_in_shopping_cart_recipe_is_in_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsamount',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='количество'),
        ),
    ]
