# Generated by Django 3.2.18 on 2023-03-12 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredientsamount_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'ингридиент', 'verbose_name_plural': 'ингридиенты'},
        ),
    ]
