# Generated by Django 3.2.18 on 2023-03-17 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20230317_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favorited',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorited', through='recipes.Favorit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.ManyToManyField(blank=True, default=None, related_name='in_shopping_cart', through='recipes.ShoppingCart', to=settings.AUTH_USER_MODEL),
        ),
    ]
